trigger:
  - "**"
pr:
  - master

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: DotNetCoreInstaller@1
        inputs:
          version: 3.1.101
        displayName: Install dotnet

      - bash: touch "$HOME/.dotnet/$(dotnet --version).dotnetFirstUseSentinel"
        displayName: Touch dotnet

      - task: Docker@2
        inputs:
          command: login
          containerRegistry: DockerHub
        displayName: Docker login

      - bash: dotnet tool restore && dotnet cake --bootstrap && dotnet cake --verbosity=verbose --target=build --publish=true
        displayName: Cake build
