trigger:
- master

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    displayName: Checkout source

  - task: DotNetCoreInstaller@1
    inputs:
      version: 3.1.100
    displayName: Install .NET Core SDK

  - task: Docker@2
    inputs:
      command: login
      containerRegistry: DockerHub
    displayName: Docker login

  - task: Cache@2
    inputs:
      path: $(NUGET_PACKAGES)
      key: $(Agent.OS)|nuget|**/packages.lock.json
      restoreKeys: |
        $(Agent.OS)|nuget
    displayName: Cache packages

  - bash: ./cake.sh --verbosity=verbose --ispublisher=true
    env:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    displayName: Cake build
