trigger:
- master

variables:
- group: Cake
- group: DotNet

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core SDK
    inputs:
      version: $(DotNet.Sdk.Version)

  - task: Docker@1
    displayName: Docker login
    inputs:
      command: login
      containerRegistryType: Container Registry
      dockerRegistryEndpoint: DockerHub

  - bash: ./cake.sh --verbosity=$(Cake.Verbosity) --ispublisher=true
    displayName: Cake build
