trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@1
    inputs:
      version: 2.2.402
    displayName: Install .NET Core SDK

  - task: Docker@2
    inputs:
      command: login
      containerRegistry: DockerHub
    displayName: Docker login

  - bash: ./cake.sh --verbosity=verbose --ispublisher=true
    displayName: Cake build
