trigger:
- master

variables:
- group: Cake
- group: DotNet

jobs:
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@1
    inputs:
      version: $(DotNet.Sdk.Version)
    displayName: Install .NET Core SDK

  - task: Docker@2
    inputs:
      command: login
      containerRegistry: DockerHub
    displayName: Docker login

  - bash: ./cake.sh --verbosity=$(Cake.Verbosity) --ispublisher=true
    displayName: Cake build
