name: Build
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402

    - name: Docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cake build
      run: ./cake.sh --verbosity=verbose --ispublisher=true
      env:
        DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.2.402/x64
