name: Build
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

env:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201

      - name: Touch dotnet
        run: touch "$HOME/.dotnet/$(dotnet --version).dotnetFirstUseSentinel"

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Cake build
        run: dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build
